services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  
  backend:
    build: ./videoapp/
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0:8000"
    depends_on:
      - db
    env_file:
      - ./videoapp/.env
    ports:
      - 8000:8000

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080